# Generated by Django 5.2.5 on 2025-09-23 16:16

import articles.models
import django.core.validators
import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_updated_at_alter_article_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articleimage',
            options={'ordering': ['uploaded_at']},
        ),
        migrations.RemoveField(
            model_name='article',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='articleimage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='articleimage',
            name='order',
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=articles.models.article_image_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif'])], verbose_name='Фотография'),
        ),
    ]
